version: '3.8'
services:
    gitlab-server:
        image: 'gitlab/gitlab-ce'
        container_name: jovial_jemison
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://localhost:8989'
                gitlab_rails['initial_root_password'] = 'Nextjs@Amit@123456'
                puma['worker_processes'] = 0 #diable cluster mode to avoid more memory usage
        volumes:
                - ./gitlab/config:/etc/gitlab
                - ./gitlab/logs:/var/log/gitlab
                - ./gitlab/data:/var/opt/gitlab
        ports:
            - '8989:8989'   

    gitlab-runner:
          image: gitlab/gitlab-runner:alpine
          container_name: gitlab-runner
          volumes:
                 - /var/run/docker.sock:/var/run/docker.sock
